-- MySQL Script generated by MySQL Workbench
-- Fri Sep 12 16:22:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema games_pendu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `games_pendu` ;

-- -----------------------------------------------------
-- Schema games_pendu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `games_pendu` DEFAULT CHARACTER SET utf8 ;
USE `games_pendu` ;

-- -----------------------------------------------------
-- Table `games_pendu`.`Themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Themes` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Themes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_pendu`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Players` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(50) NULL,
  `totalscore` INT NULL,
  `Themes_favorite_id` INT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
  INDEX `fk_Players_Themes_idx` (`Themes_favorite_id` ASC) VISIBLE,
  CONSTRAINT `fk_Players_Themes`
    FOREIGN KEY (`Themes_favorite_id`)
    REFERENCES `games_pendu`.`Themes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_pendu`.`Letters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Letters` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Letters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1) NULL,
  `iscorrect` TINYINT ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_pendu`.`Words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Words` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Words` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(50) NULL,
  `Themes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE,
  INDEX `fk_Words_Themes1_idx` (`Themes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Words_Themes1`
    FOREIGN KEY (`Themes_id`)
    REFERENCES `games_pendu`.`Themes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_pendu`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Games` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_hours` DATETIME NULL,
  `result` VARCHAR(20) NULL,
  `nb_error` INT NULL,
  `Players_id` INT NOT NULL,
  `Words_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Games_Players1_idx` (`Players_id` ASC) VISIBLE,
  INDEX `fk_Games_Words1_idx` (`Words_id` ASC) VISIBLE,
  CONSTRAINT `fk_Games_Players1`
    FOREIGN KEY (`Players_id`)
    REFERENCES `games_pendu`.`Players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Games_Words1`
    FOREIGN KEY (`Words_id`)
    REFERENCES `games_pendu`.`Words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `games_pendu`.`Letters_hasin_Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `games_pendu`.`Letters_hasin_Games` ;

CREATE TABLE IF NOT EXISTS `games_pendu`.`Letters_hasin_Games` (
  `Letters_id` INT NOT NULL,
  `Games_id` INT NOT NULL,
  PRIMARY KEY (`Letters_id`, `Games_id`),
  INDEX `fk_Letters_has_Games_Games1_idx` (`Games_id` ASC) VISIBLE,
  INDEX `fk_Letters_has_Games_Letters1_idx` (`Letters_id` ASC) VISIBLE,
  CONSTRAINT `fk_Letters_has_Games_Letters1`
    FOREIGN KEY (`Letters_id`)
    REFERENCES `games_pendu`.`Letters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Letters_has_Games_Games1`
    FOREIGN KEY (`Games_id`)
    REFERENCES `games_pendu`.`Games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
